name: Build and Download node_modules
on:
  workflow_dispatch:  # 手動觸發
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip node_modules
        run: touch qaq.txt
      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v4
        with:
          name: qaq
          path: qaq.txt